package io.statemodeler.cli.commands;

import static org.junit.jupiter.api.Assertions.*;

import io.statemodeler.cli.Main;
import io.statemodeler.cli.RepositoryMixin;
import io.statemodeler.repository.H2SdrRepository;
import io.statemodeler.sdr.SdrRecord;
import java.io.File;
import java.nio.file.Files;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import picocli.CommandLine;

/**
 * Tests for {@link MigrateCommand}.
 *
 * <p>Note: Tests requiring actual LLM execution are disabled as they need:
 * - Ollama server running locally
 * These tests validate CLI argument parsing, repository integration, and error handling.
 */
class MigrateCommandTest {

    @TempDir
    File tempDir;

    private H2SdrRepository repository;
    // Do not capture stdout/stderr in tests; assert based on repository state and exit codes

    @BeforeEach
    void setUp() {
        // Use in-memory database for faster tests
        repository = H2SdrRepository.createInMemory("test-migrate-" + System.nanoTime());

        // No stdout/stderr capture; rely on exit code and repository state
    }

    @AfterEach
    void tearDown() {
        if (repository != null) {
            repository.close();
        }
        // No stdout/stderr capture to restore
    }

    @Test
    void shouldFailWhenSourceSdrNotFound() {
        // Given
        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "nonexistent";
        cmd.toIdentifier = "hash2";
        cmd.dialect = "postgres";
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When
        int exitCode = cmd.call();

        // Then
        assertEquals(1, exitCode);
        var found = repository.findByHash("nonexistent");
        assertTrue(found.isSuccess());
        assertTrue(found.get().isEmpty());
    }

    @Test
    void shouldFailWhenTargetSdrNotFound() {
        // Given
        var sdr1 = createTestSdr("hash1", "CREATE TABLE test;");
        repository.save(sdr1, "test-model", "1.0").get();

        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "hash1";
        cmd.toIdentifier = "nonexistent";
        cmd.dialect = "postgres";
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When
        int exitCode = cmd.call();

        // Then
        assertEquals(1, exitCode);
        var maybeTarget = repository.findByHash("nonexistent");
        assertTrue(maybeTarget.isSuccess());
        assertTrue(maybeTarget.get().isEmpty());
    }

    @Test
    void shouldRejectUnsupportedDialect() {
        // Given
        var sdr1 = createTestSdr("hash1", "CREATE TABLE test;");
        var sdr2 = createTestSdr("hash2", "CREATE TABLE test2;");
        repository.save(sdr1, "test-model", "1.0").get();
        repository.save(sdr2, "test-model", "2.0").get();

        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "hash1";
        cmd.toIdentifier = "hash2";
        cmd.dialect = "mysql"; // Unsupported
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When
        int exitCode = cmd.call();

        // Then
        assertEquals(1, exitCode);
    }

    @Test
    void shouldReuseExistingMigrationByDefault() {
        // Given - create migration first
        var sdr1 = createTestSdr("hash1", "CREATE TABLE test;");
        var sdr2 = createTestSdr("hash2", "CREATE TABLE test2;");
        repository.save(sdr1, "test-model", "1.0").get();
        repository.save(sdr2, "test-model", "2.0").get();

        var migration = new io.statemodeler.repository.SdrMigration(
                "hash1",
                "hash2",
                "-- Existing migration",
                0.9,
                "Generated by test",
                "postgres",
                java.time.Instant.now());
        repository.saveMigration(migration).get();

        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "hash1";
        cmd.toIdentifier = "hash2";
        cmd.dialect = "postgres";
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When
        int exitCode = cmd.call();

        // Then
        assertEquals(0, exitCode);
        var foundMigration = repository.findMigration("hash1", "hash2");
        assertTrue(foundMigration.isSuccess());
        assertTrue(foundMigration.get().isPresent());
        assertEquals(migration.migrationScript(), foundMigration.get().get().migrationScript());
    }

    @Test
    void shouldHaveMigrateSubcommandInMain() {
        // Given
        var main = new Main();
        var cmd = new CommandLine(main);

        // When
        var subcommands = cmd.getSubcommands();

        // Then
        assertTrue(subcommands.containsKey("migrate"));
    }

    @Test
    void shouldFindSdrByNameAndVersion() {
        // Given
        var sdr1 = createTestSdr("hash1", "CREATE TABLE test;");
        var sdr2 = createTestSdr("hash2", "CREATE TABLE test2;");
        repository.save(sdr1, "orders", "1.0").get();
        repository.save(sdr2, "orders", "2.0").get();

        var migration = new io.statemodeler.repository.SdrMigration(
                "hash1", "hash2", "-- Migration script", 0.9, "Generated by test", "postgres", java.time.Instant.now());
        repository.saveMigration(migration).get();

        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "orders:1.0"; // Name:version format
        cmd.toIdentifier = "orders:2.0"; // Name:version format
        cmd.dialect = "postgres";
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When
        int exitCode = cmd.call();

        // Then
        assertEquals(0, exitCode);
        var foundMigration2 = repository.findMigration("hash1", "hash2");
        assertTrue(foundMigration2.isSuccess());
        assertTrue(foundMigration2.get().isPresent());
        assertEquals(migration.migrationScript(), foundMigration2.get().get().migrationScript());
    }

    @Test
    void shouldHandleInvalidNameVersionFormat() {
        // Given
        var sdr = createTestSdr("hash1", "CREATE TABLE test;");
        repository.save(sdr, "model", "1.0").get();

        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "model:"; // Invalid - missing version
        cmd.toIdentifier = "hash1";
        cmd.dialect = "postgres";
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When
        int exitCode = cmd.call();

        // Then - should attempt to find by name only (latest version)
        assertEquals(1, exitCode); // Fails because toIdentifier doesn't exist
    }

    @Test
    void shouldUseDefaultModelName() {
        // Given - model name not specified, should use default
        var cmd = new MigrateCommand();
        cmd.llmProvider = "ollama";
        cmd.modelName = null; // Not specified

        // When/Then - verify command initializes (can't test full execution without LLM)
        assertNotNull(cmd);
        assertEquals("ollama", cmd.llmProvider);
        assertNull(cmd.modelName); // Will use default in createLlmModel()
    }

    @Test
    void shouldRequireOpenAiApiKeyWhenProviderOpenAi() throws Exception {
        // Given
        var cmd = new MigrateCommand();
        cmd.llmProvider = "openai";
        cmd.modelName = "gpt-4o-mini";

        // When - createLlmModel is private; call via reflection
        var method = MigrateCommand.class.getDeclaredMethod("createLlmModel");
        method.setAccessible(true);

        // Then - behavior depends on environment: if OPENAI_API_KEY env var is not set, expect exception
        String apiKey = System.getenv("OPENAI_API_KEY");
        if (apiKey == null || apiKey.isBlank()) {
            Exception exception = assertThrows(Exception.class, () -> method.invoke(cmd));
            String message = exception.getCause() != null ? exception.getCause().getMessage() : exception.getMessage();
            assertTrue(message.contains("OPENAI_API_KEY is required"));
        } else {
            // If API key is present in environment, ensure createLlmModel doesn't throw
            method.invoke(cmd);
        }
    }

    @Test
    void shouldUseCustomModelName() {
        // Given
        var cmd = new MigrateCommand();
        cmd.llmProvider = "ollama";
        cmd.modelName = "llama3.2";

        // When/Then
        assertNotNull(cmd);
        assertEquals("llama3.2", cmd.modelName);
    }

    @Test
    void shouldHandleForceFlag() {
        // Given - migration exists but --force is set
        var sdr1 = createTestSdr("hash1", "CREATE TABLE test;");
        var sdr2 = createTestSdr("hash2", "CREATE TABLE test2;");
        repository.save(sdr1, "test-model", "1.0").get();
        repository.save(sdr2, "test-model", "2.0").get();

        var migration = new io.statemodeler.repository.SdrMigration(
                "hash1", "hash2", "-- Old migration", 0.9, "Generated by test", "postgres", java.time.Instant.now());
        repository.saveMigration(migration).get();

        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "hash1";
        cmd.toIdentifier = "hash2";
        cmd.dialect = "postgres";
        cmd.force = true; // Should NOT reuse existing
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When - would generate new migration (but fails without real LLM)
        int exitCode = cmd.call();

        // Then - attempts generation (fails at LLM execution stage)
        assertEquals(1, exitCode); // Fails because we don't have LLM model
        // Existing migration should remain unchanged
        var foundMigration3 = repository.findMigration("hash1", "hash2");
        assertTrue(foundMigration3.isSuccess());
        assertTrue(foundMigration3.get().isPresent());
        assertEquals(migration.migrationScript(), foundMigration3.get().get().migrationScript());
    }

    @Test
    void shouldWriteOutputToFile() throws Exception {
        // Given - migration already exists
        var sdr1 = createTestSdr("hash1", "CREATE TABLE test;");
        var sdr2 = createTestSdr("hash2", "CREATE TABLE test2;");
        repository.save(sdr1, "test-model", "1.0").get();
        repository.save(sdr2, "test-model", "2.0").get();

        var migration = new io.statemodeler.repository.SdrMigration(
                "hash1",
                "hash2",
                "-- Test migration script\nBEGIN;\nCOMMIT;",
                0.9,
                "Generated by test",
                "postgres",
                java.time.Instant.now());
        repository.saveMigration(migration).get();

        var outputFile = new File(tempDir, "migration.sql");
        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "hash1";
        cmd.toIdentifier = "hash2";
        cmd.dialect = "postgres";
        cmd.outputFile = outputFile;
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When
        int exitCode = cmd.call();

        // Then
        assertEquals(0, exitCode);
        assertTrue(outputFile.exists());
        String fileContent = Files.readString(outputFile.toPath());
        assertTrue(fileContent.contains("Test migration script"));
    }

    @Test
    void shouldWriteOutputJsonToFile() throws Exception {
        // Given - migration already exists
        var sdr1 = createTestSdr("hash1", "CREATE TABLE test;");
        var sdr2 = createTestSdr("hash2", "CREATE TABLE test2;");
        repository.save(sdr1, "test-model", "1.0").get();
        repository.save(sdr2, "test-model", "2.0").get();

        var migration = new io.statemodeler.repository.SdrMigration(
                "hash1",
                "hash2",
                "-- Test migration script\nBEGIN;\nCOMMIT;",
                0.9,
                "Generated by test",
                "postgres",
                java.time.Instant.now());
        repository.saveMigration(migration).get();

        var outputJsonFile = new File(tempDir, "migration.json");
        var cmd = new MigrateCommand();
        cmd.fromIdentifier = "hash1";
        cmd.toIdentifier = "hash2";
        cmd.dialect = "postgres";
        cmd.outputJson = outputJsonFile;
        cmd.repositoryMixin = new RepositoryMixin();
        cmd.repositoryMixin.testRepository = repository;

        // When
        int exitCode = cmd.call();

        // Then
        assertEquals(0, exitCode);
        assertTrue(outputJsonFile.exists());
        String jsonContent = Files.readString(outputJsonFile.toPath());
        assertTrue(jsonContent.contains("Test migration script"));
    }

    private SdrRecord createTestSdr(String hash, String ddl) {
        String schema = "{\"name\":\"test\"}";
        return new SdrRecord(schema, "application/json", ddl, hash, "ddl-hash-" + hash, "1.0.0");
    }
}
