package io.statemodeler.repository;

import java.time.Instant;

/**
 * Represents a migration script between two SdrMetadata versions.
 *
 * <p>Stores the SQL migration script generated by the MigrationGenerationService to transition from
 * one schema version to another, along with LLM metadata (confidence and comments).
 *
 * @param fromHash SHA-256 hash of the source SdrMetadata
 * @param toHash SHA-256 hash of the target SdrMetadata
 * @param migrationScript SQL script to migrate from source to target
 * @param confidence LLM's confidence in the migration script (0.0 to 1.0)
 * @param comments LLM's explanation and reasoning about the migration
 * @param dialect database dialect (e.g., "postgres")
 * @param createdAt timestamp when this migration was generated
 */
public record SdrMigration(
        String fromHash,
        String toHash,
        String migrationScript,
        double confidence,
        String comments,
        String dialect,
        Instant createdAt) {

    /**
     * Creates a new SdrMigration with validation.
     *
     * @throws IllegalArgumentException if any field is null or blank, or confidence out of range
     */
    public SdrMigration {
        if (fromHash == null || fromHash.isBlank()) {
            throw new IllegalArgumentException("fromHash cannot be null or blank");
        }
        if (toHash == null || toHash.isBlank()) {
            throw new IllegalArgumentException("toHash cannot be null or blank");
        }
        if (migrationScript == null || migrationScript.isBlank()) {
            throw new IllegalArgumentException("migrationScript cannot be null or blank");
        }
        if (confidence < 0.0 || confidence > 1.0) {
            throw new IllegalArgumentException("confidence must be between 0.0 and 1.0, got: " + confidence);
        }
        if (comments == null || comments.isBlank()) {
            throw new IllegalArgumentException("comments cannot be null or blank");
        }
        if (dialect == null || dialect.isBlank()) {
            throw new IllegalArgumentException("dialect cannot be null or blank");
        }
        if (createdAt == null) {
            throw new IllegalArgumentException("createdAt cannot be null");
        }
    }
}
