plugins {
    id("org.springframework.boot") version "3.2.3"
    id("io.spring.dependency-management") version "1.1.4"
}

dependencies {
    implementation(project(":state-modeler-core"))
    implementation("org.springframework.boot:spring-boot-starter-data-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-web")
    runtimeOnly("com.h2database:h2")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.test {
    useJUnitPlatform()
}

// Simple task to run the generator (assuming we can invoke it via JavaExec or similar if we had a main class, 
// but here we might need to write a small script or custom task class. 
// For now, let's just rely on the fact that we can run the tests which verify generation, 
// OR we can try to use the CLI app if we build it.
// But the user asked to "test our code generation", implying we should probably generate the code and see if it compiles/runs.
// Let's add a task that uses the Core API to generate code into src/main/java.

// Gradle wrapper task `generateCode` is implemented below using Exec to call the helper script.

// A Gradle task wrapper that executes the helper script for code generation.
// This is useful so you can call `./gradlew :sample:generateCode` to generate
// the sources and have them included in compilation.
val defaultModelFile = project.rootProject.file("scripts/examples/orders-sdd-mini-model.yaml").absolutePath
val modelFileUsed = (project.findProperty("sddModelFile") as String?) ?: defaultModelFile
val modelFileUsedAbs = project.rootProject.file(modelFileUsed).absolutePath

val sddOutDirProp = (project.findProperty("sddOutDir") as String?) ?: "${project.buildDir}/generated/sdd"
val sddOutDirAbs = project.file(sddOutDirProp).absolutePath
val sddLanguageProp = (project.findProperty("sddLanguage") as String?) ?: "java"
val sddAddToSourceSet = (project.findProperty("sddAddToSourceSet") as String?)?.toBoolean() ?: true

val generateCode by tasks.registering(Exec::class) {
    group = "sdd"
    description = "Runs the scripts/generate-code.sh helper to produce generated sources for the sample module"

    val scriptPath = project.rootProject.file("scripts/generate-code.sh").absolutePath
    // Use bash to execute the script so it doesn't need to be executable
        commandLine("bash", scriptPath,
            "-m", modelFileUsedAbs,
            "-o", sddOutDirAbs,
            "-l", sddLanguageProp,
            "--skip-build",
            "--no-format")

    // Mark outputs so Gradle sees task as incremental
    outputs.dir(sddOutDirAbs)

    doFirst {
        println("Generating sources from model: $modelFileUsed into $sddOutDirProp")
        // Ensure out dir exists
        project.file(sddOutDirAbs).mkdirs()
    }
}

// Integrate the generated code into the main source set so compilation picks it up
if (sddAddToSourceSet) {
    sourceSets.main.get().java.srcDir(sddOutDirAbs)
}

// Exclude old top-level generated files from the sample module's main sources to avoid conflicts
// These files are generated by the CLI and not meant to be manually maintained in sample/src/main/java
sourceSets.main.get().java {
    exclude(
        "com/example/*State.java",
        "com/example/*Id.java",
        "com/example/*Repository.java",
        "com/example/*Converters.java",
        "com/example/SddConfig.java"
    )
}

// Exclude the generated sources from Spotless formatting checks for the sample project,
// since generated code should not interfere with the hand-written code formatting rules.
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    java {
        targetExclude("$sddOutDirAbs/**")
    }
}

// Ensure the generated sources exist before we compile
if (sddAddToSourceSet) {
    tasks.named("compileJava") {
        dependsOn(generateCode)
    }
}
