package io.statemodeler.repository;

import static org.junit.jupiter.api.Assertions.*;

import java.time.Instant;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Tests for {@link SdrMigration} record.
 */
class SdrMigrationTest {

    @Test
    void shouldCreateValidMigration() {
        // Given
        var now = Instant.now();

        // When
        var migration =
                new SdrMigration("hash1", "hash2", "ALTER TABLE test;", 0.9, "Generated by test", "postgres", now);

        // Then
        assertEquals("hash1", migration.fromHash());
        assertEquals("hash2", migration.toHash());
        assertEquals("ALTER TABLE test;", migration.migrationScript());
        assertEquals("postgres", migration.dialect());
        assertEquals(now, migration.createdAt());
    }

    @ParameterizedTest(name = "{6}")
    @MethodSource("provideInvalidParameterCases")
    void shouldRejectInvalidParameters(
            String fromHash,
            String toHash,
            String migrationScript,
            double confidence,
            String comments,
            String dialect,
            Instant createdAt,
            String expectedMessage) {
        // When/Then
        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> new SdrMigration(fromHash, toHash, migrationScript, confidence, comments, dialect, createdAt));
        assertEquals(expectedMessage, exception.getMessage());
    }

    static Stream<Arguments> provideInvalidParameterCases() {
        String validHash = "hash1";
        String validScript = "ALTER TABLE test;";
        double validConfidence = 0.9;
        String validComments = "Generated by test";
        String validDialect = "postgres";
        Instant validTime = Instant.now();

        return Stream.of(
                Arguments.of(
                        null,
                        validHash,
                        validScript,
                        validConfidence,
                        validComments,
                        validDialect,
                        validTime,
                        "fromHash cannot be null or blank"),
                Arguments.of(
                        "",
                        validHash,
                        validScript,
                        validConfidence,
                        validComments,
                        validDialect,
                        validTime,
                        "fromHash cannot be null or blank"),
                Arguments.of(
                        validHash,
                        null,
                        validScript,
                        validConfidence,
                        validComments,
                        validDialect,
                        validTime,
                        "toHash cannot be null or blank"),
                Arguments.of(
                        validHash,
                        "",
                        validScript,
                        validConfidence,
                        validComments,
                        validDialect,
                        validTime,
                        "toHash cannot be null or blank"),
                Arguments.of(
                        validHash,
                        validHash,
                        null,
                        validConfidence,
                        validComments,
                        validDialect,
                        validTime,
                        "migrationScript cannot be null or blank"),
                Arguments.of(
                        validHash,
                        validHash,
                        "   ",
                        validConfidence,
                        validComments,
                        validDialect,
                        validTime,
                        "migrationScript cannot be null or blank"),
                Arguments.of(
                        validHash,
                        validHash,
                        validScript,
                        validConfidence,
                        validComments,
                        null,
                        validTime,
                        "dialect cannot be null or blank"),
                Arguments.of(
                        validHash,
                        validHash,
                        validScript,
                        validConfidence,
                        validComments,
                        "",
                        validTime,
                        "dialect cannot be null or blank"),
                Arguments.of(
                        validHash,
                        validHash,
                        validScript,
                        validConfidence,
                        validComments,
                        validDialect,
                        null,
                        "createdAt cannot be null"));
    }

    @Test
    void shouldSupportRecordEquality() {
        // Given
        var now = Instant.now();
        var migration1 =
                new SdrMigration("hash1", "hash2", "ALTER TABLE test;", 0.9, "Generated by test", "postgres", now);
        var migration2 =
                new SdrMigration("hash1", "hash2", "ALTER TABLE test;", 0.9, "Generated by test", "postgres", now);
        var migration3 =
                new SdrMigration("hash1", "hash3", "ALTER TABLE test;", 0.9, "Generated by test", "postgres", now);

        // Then
        assertEquals(migration1, migration2);
        assertNotEquals(migration1, migration3);
    }

    @Test
    void shouldSupportRecordToString() {
        // Given
        var migration = new SdrMigration(
                "hash1", "hash2", "ALTER TABLE test;", 0.9, "Generated by test", "postgres", Instant.now());

        // Then
        String str = migration.toString();
        assertTrue(str.contains("hash1"));
        assertTrue(str.contains("hash2"));
        assertTrue(str.contains("postgres"));
    }
}
