package io.statemodeler.repository;

/**
 * Test constants for SdrMigration objects.
 *
 * <p>Provides default values for confidence and comments to avoid repetition in tests.
 */
public final class TestMigrationConstants {

    /** Default confidence value for test migrations (0.9 = 90% confidence). */
    public static final double DEFAULT_CONFIDENCE = 0.9;

    /** Default comments for test migrations. */
    public static final String DEFAULT_COMMENTS = "Generated by test";

    private TestMigrationConstants() {
        // Utility class
    }
}
